### ISSUE TITLE
Kanban Board 

### ISSUE THREAD

**Issue by andrianarivo** [andrianarivo/recipe_app#12]
- Link to our project: [Project](https://github.com/users/andrianarivo/projects/5)
- We are a team of 2 members
  - Team member 1: @andrianarivo
  - Team member 2: @rachaouldbabaali

**Comment by julie-ify** [comment]
## Hi @andrianarivo and @rachaouldbabaali,

Good job so far!

## Highlights!
- Descriptive issue ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly add the task for the tests.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rachaouldbabaali** [comment]
Thank you @julie-ify  for your feedback. We appreciate your time and attention to detail. We would like to inform you that we have already included the task for the tests in each task. 

![image](https://github.com/andrianarivo/recipe_app/assets/33148222/2b68a885-361f-444e-a90f-f1156b185705)

**Comment by brainconnect93** [comment]
## Status: Approved :heavy_check_mark:

Hi @andrianarivo & @rachaouldbabaali, 👋 👋  

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Task properly assigned ✔️
- kanban board created ✔️
- Descriptive issues✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
